// Generated by extract.py from Swift 0.1.122 (pi-app 6319e368). Do not edit.
import Foundation

// TranscriptActivity.swift:5-11
enum DurationObservation {
    static func valid(_ milliseconds: Double?) -> Double? {
        guard let milliseconds, milliseconds.isFinite, milliseconds >= 0,
              milliseconds < Double(Int.max) else { return nil }
        return milliseconds
    }
}

// TranscriptActivity.swift:18
enum ActionKind: String, Sendable { case command, read, write, search, list, mcp, other }

// TranscriptActivity.swift:20-25
struct ActionDescription: Equatable, Sendable {
    let kind: ActionKind
    let verb: String
    let object: String
    var path: String? = nil
}

// TranscriptActivity.swift:30
enum ActionOutcome: String, Sendable { case running, done, failed, cancelled, unknown }

// TranscriptActivity.swift:36-45
enum ToolState {
    /// Not finished: its arguments are arriving or complete, or it runs.
    static let inFlight: Set<String> = ["running", "preparing", "prepared"]
    /// Still producing: its arguments or its output are arriving. A change to
    /// such a call may wait for the next presentation (`TaskTranscriptPlan.cosmetic`).
    static let producing: Set<String> = ["preparing", "running"]
    /// Its card does not carry the call's result: the call is not finished,
    /// or the card was read back holding only the request ("recorded").
    static let withoutResult: Set<String> = ["preparing", "prepared", "running", "recorded"]
}

// TranscriptRowChrome.swift:35-48
enum TranscriptRowState: String, Sendable, Equatable {
    case ok, running, stopped, failed

    /// The word assistive technology hears, since the dot and the sweep are
    /// both colour.
    var spokenStatus: String? {
        switch self {
        case .ok: return nil
        case .running: return "Running"
        case .stopped: return "Stopped"
        case .failed: return "Failed"
        }
    }
}

// TranscriptRows.swift:49-59
nonisolated func actionSymbol(_ kind: ActionKind) -> String {
    switch kind {
    case .command: return "terminal"
    case .write: return "pencil"
    case .read: return "doc.text"
    case .list: return "folder"
    case .search: return "magnifyingglass"
    case .mcp: return "point.3.connected.trianglepath.dotted"
    case .other: return "circle"
    }
}

// TranscriptRowParts.swift:183-211
enum TranscriptReadCardText {
    /// A read's result as the card reads it: its lines, and the host's note
    /// when the read stopped short of the file. The host ends a bounded read
    /// with "[Truncated. N total lines; read another range.]": a note about
    /// the file, not its next line.
    nonisolated static func window(of text: String) -> (lines: [String], note: String?) {
        var lines = text.isEmpty ? [] : text.components(separatedBy: "\n")
        if let last = lines.last, last.hasPrefix("[Truncated."), last.hasSuffix("]") {
            let note = String(last.dropFirst().dropLast())
            lines.removeLast()
            return (lines, note)
        }
        return (lines, nil)
    }
    /// The line a read started at, from its arguments: the host's `offset`, a
    /// 1-based line number, or the first line when the read named none.
    nonisolated static func firstLine(of input: String) -> Int {
        guard let offset = TranscriptActivity.parseInput(input)["offset"] as? NSNumber,
              CFGetTypeID(offset) != CFBooleanGetTypeID() else { return 1 }
        let value = offset.doubleValue
        guard value.isFinite, value >= 1, value.rounded() == value, value <= 10_000_000 else { return 1 }
        return Int(value)
    }
    /// "Showing 12 of 340 lines", and nothing at all when it is showing all
    /// of them: a card that is complete should not say so on every read.
    nonisolated static func window(shown: Int, total: Int) -> String {
        shown >= total ? "\(total) line\(total == 1 ? "" : "s")" : "Showing \(shown) of \(total) lines"
    }
}

// ToolCallSummary.swift:5-42
struct ToolCallSummary: Equatable, Sendable {
    var total = 0
    var failed = 0
    var skipped = 0
    var uncertain = 0
    var preparing = false
    var partial = false

    init(rows: [TranscriptMessage]) {
        var owners = Set<String>()
        for row in rows where row.role == "assistant" && owners.insert(row.id).inserted {
            let cards = row.tools ?? []
            let confirmed = cards.filter { $0.state != "preparing" }
            if let count = row.toolCallCount, count >= 0 { total += count }
            else { total += confirmed.count; partial = partial || row.truncated == true }
            preparing = preparing || cards.contains { $0.state == "preparing" }
            for card in confirmed {
                switch card.state {
                case "failed": failed += 1
                case "cancelled", "skipped": skipped += 1
                case "recorded", "unknown", "interrupted": uncertain += 1
                default: break
                }
            }
        }
    }
    init(tools: [ToolView]) { self.init(rows: [.init(id: "summary", role: "assistant", text: "", tools: tools)]) }
    var label: String? { label(reasoned: false) }
    func label(reasoned: Bool) -> String? {
        var parts: [String] = reasoned ? ["Reasoned"] : []
        if total > 0 { parts.append((partial ? "at least " : "") + "\(total) tool " + (total == 1 ? "call" : "calls")) }
        if failed > 0 { parts.append("\(failed) failed") }
        if skipped > 0 { parts.append("\(skipped) skipped") }
        if uncertain > 0 { parts.append("\(uncertain) outcome unknown") }
        if preparing { parts.append("Preparing tool call…") }
        return parts.isEmpty ? nil : parts.joined(separator: " · ")
    }
}

enum TranscriptActivity {
// TranscriptActivity.swift:56
    static func parseInput(_ input: String) -> [String: Any] { decodeArguments(input).values }
// TranscriptActivity.swift:58
    private static let argumentCountLock = NSLock()
// TranscriptActivity.swift:59
    nonisolated(unsafe) private static var argumentBytes = 0
// TranscriptActivity.swift:72-84
    static func decodeArguments(_ input: String) -> (values: [String: Any], complete: Bool) {
        argumentCountLock.lock(); argumentBytes += input.utf8.count; argumentCountLock.unlock()
        let data = Data(input.utf8)
        if let object = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any] {
            return (object, true)
        }
        for candidate in repairedArguments(data) {
            if let object = (try? JSONSerialization.jsonObject(with: candidate)) as? [String: Any] {
                return (object, false)
            }
        }
        return ([:], false)
    }
// TranscriptActivity.swift:90-115
    private static func repairedArguments(_ input: Data) -> [Data] {
        var bytes = [UInt8](input)
        // A cut inside an escape leaves a backslash with nothing to escape.
        while bytes.last == JSONByte.backslash { bytes.removeLast() }
        guard bytes.first == JSONByte.openObject else { return [] }
        var stack: [UInt8] = [], inString = false, escaped = false
        var lastMemberEnd: Int? = nil
        for (index, byte) in bytes.enumerated() {
            if escaped { escaped = false; continue }
            if byte == JSONByte.backslash { if inString { escaped = true }; continue }
            if byte == JSONByte.quote { inString.toggle(); continue }
            if inString { continue }
            switch byte {
            case JSONByte.openObject, JSONByte.openArray: stack.append(byte)
            case JSONByte.closeObject, JSONByte.closeArray: if !stack.isEmpty { stack.removeLast() }
            case JSONByte.comma: if stack.count == 1 { lastMemberEnd = index }
            default: break
            }
        }
        var closed = bytes
        if inString { closed.append(JSONByte.quote) }
        for opener in stack.reversed() { closed.append(opener == JSONByte.openObject ? JSONByte.closeObject : JSONByte.closeArray) }
        var candidates = [Data(closed)]
        if let lastMemberEnd { candidates.append(Data(bytes[..<lastMemberEnd] + [JSONByte.closeObject])) }
        return candidates
    }
// TranscriptActivity.swift:116-120
    private enum JSONByte {
        static let quote = UInt8(ascii: "\""), backslash = UInt8(ascii: "\\"), comma = UInt8(ascii: ","), colon = UInt8(ascii: ":")
        static let openObject = UInt8(ascii: "{"), closeObject = UInt8(ascii: "}"), openArray = UInt8(ascii: "["), closeArray = UInt8(ascii: "]")
        static func isSpace(_ byte: UInt8) -> Bool { byte == 0x20 || byte == 0x09 || byte == 0x0A || byte == 0x0D }
    }
// TranscriptActivity.swift:130-134
    static func argumentString(_ key: String, in input: String) -> String? {
        let name = Array(key.utf8)
        if let found = input.utf8.withContiguousStorageIfAvailable({ member(name, in: $0) }) { return found }
        return Array(input.utf8).withUnsafeBufferPointer { member(name, in: $0) }
    }
// TranscriptActivity.swift:135-214
    private static func member(_ name: [UInt8], in bytes: UnsafeBufferPointer<UInt8>) -> String? {
        let count = bytes.count
        var index = 0
        func skipSpace() { while index < count, JSONByte.isSpace(bytes[index]) { index += 1 } }
        /// The index past a string token's closing quote, or nil when the
        /// document ends inside it.
        func stringEnd(from start: Int) -> Int? {
            var cursor = start + 1
            while cursor < count {
                switch bytes[cursor] {
                case JSONByte.backslash: cursor += 2
                case JSONByte.quote: return cursor + 1
                default: cursor += 1
                }
            }
            return nil
        }
        /// Skips one value; false when the document ends inside it.
        func skipValue() -> Bool {
            guard index < count else { return false }
            switch bytes[index] {
            case JSONByte.quote:
                guard let end = stringEnd(from: index) else { return false }
                index = end; return true
            case JSONByte.openObject, JSONByte.openArray:
                var depth = 0
                while index < count {
                    switch bytes[index] {
                    case JSONByte.quote:
                        guard let end = stringEnd(from: index) else { return false }
                        index = end; continue
                    case JSONByte.openObject, JSONByte.openArray: depth += 1
                    case JSONByte.closeObject, JSONByte.closeArray:
                        depth -= 1
                        if depth == 0 { index += 1; return true }
                    default: break
                    }
                    index += 1
                }
                return false
            default:
                while index < count, bytes[index] != JSONByte.comma, bytes[index] != JSONByte.closeObject, !JSONByte.isSpace(bytes[index]) { index += 1 }
                return index < count
            }
        }
        func decoded(_ token: ArraySlice<UInt8>) -> String? {
            (try? JSONSerialization.jsonObject(with: Data(token), options: .fragmentsAllowed)) as? String
        }
        skipSpace()
        guard index < count, bytes[index] == JSONByte.openObject else { return nil }
        index += 1
        while true {
            skipSpace()
            guard index < count, bytes[index] == JSONByte.quote, let keyEnd = stringEnd(from: index) else { return nil }
            let key = UnsafeBufferPointer(rebasing: bytes[(index + 1)..<(keyEnd - 1)])
            // A key written with escapes is compared as the key it decodes to.
            let matches = key.elementsEqual(name) || (key.contains(JSONByte.backslash) && decoded(ArraySlice(bytes[index..<keyEnd])).map { Array($0.utf8) == name } == true)
            index = keyEnd
            skipSpace()
            guard index < count, bytes[index] == JSONByte.colon else { return nil }
            index += 1
            skipSpace()
            guard index < count else { return nil }
            if matches {
                guard bytes[index] == JSONByte.quote else { return nil }
                if let end = stringEnd(from: index) { return decoded(ArraySlice(bytes[index..<end])) }
                // Cut inside the value: close what arrived, without a
                // backslash left with nothing to escape.
                var partial = Array(bytes[index..<count])
                var trailing = 0
                while partial.count - trailing > 1, partial[partial.count - 1 - trailing] == JSONByte.backslash { trailing += 1 }
                if trailing % 2 == 1 { partial.removeLast() }
                return decoded(ArraySlice(partial + [JSONByte.quote]))
            }
            guard skipValue() else { return nil }
            skipSpace()
            guard index < count, bytes[index] == JSONByte.comma else { return nil }
            index += 1
        }
    }
// TranscriptActivity.swift:215-218
    static func shortPath(_ path: String) -> String {
        let parts = path.split(separator: "/").filter { !$0.isEmpty }
        return parts.count > 2 ? parts.suffix(2).joined(separator: "/") : path
    }
// TranscriptActivity.swift:222-227
    static func firstLine(_ text: String, max: Int = 96) -> String {
        let scalars = text.unicodeScalars
        let end = scalars.firstIndex(of: "\n") ?? scalars.endIndex
        let line = String(Substring(scalars[..<end])).trimmingCharacters(in: .whitespacesAndNewlines)
        return line.count > max ? String(line.prefix(max - 1)) + "…" : line
    }
// TranscriptActivity.swift:234
    private static let blank = CharacterSet.whitespacesAndNewlines
// TranscriptActivity.swift:235-238
    private static func text(_ value: Any?) -> String? {
        guard let string = value as? String, !string.isEmpty else { return nil }
        return string
    }
// TranscriptActivity.swift:239-247
    static func outcome(of tool: ToolView) -> ActionOutcome {
        if ToolState.inFlight.contains(tool.state) { return .running }
        if tool.state == "cancelled" { return .cancelled }
        if tool.state == "failed" { return .failed }
        // Sent only to an app that says it reads it (the hello's
        // `unknownToolOutcomes`); an older app sees "cancelled" or "failed".
        if tool.state == "unknown" { return .unknown }
        return .done
    }
// TranscriptActivity.swift:270-278
    private static func conjugate(_ done: String, _ doing: String, _ outcome: ActionOutcome) -> String {
        switch outcome {
        case .running: return doing.prefix(1).uppercased() + doing.dropFirst()
        case .failed: return "Failed " + doing
        case .cancelled: return "Skipped " + doing
        case .unknown: return "Stopped " + doing
        case .done: return done
        }
    }
// TranscriptActivity.swift:280
    static func describe(_ tool: ToolView) -> ActionDescription { describe(actionParts(tool), outcome: outcome(of: tool)) }
// TranscriptActivity.swift:281-283
    static func describe(_ parts: ActionParts, outcome: ActionOutcome) -> ActionDescription {
        ActionDescription(kind: parts.kind, verb: conjugate(parts.done, parts.doing, outcome), object: parts.object, path: parts.path)
    }
// TranscriptActivity.swift:288-294
    struct ActionParts: Equatable, Sendable {
        let kind: ActionKind
        let done: String
        let doing: String
        let object: String
        var path: String? = nil
    }
// TranscriptActivity.swift:295-332
    static func actionParts(_ tool: ToolView) -> ActionParts {
        switch tool.name {
        case "read", "write", "edit", "ls":
            // Native file tools report their resolved path once they run.
            // Until then the path is the one member read out of arguments that
            // can carry a whole file or edit behind it — never the whole document.
            // A read says the path it was given, as it always has: the one the
            // host resolved (since it names it) is where its link opens.
            let path = tool.name == "read" ? text(argumentString("path", in: tool.input)) ?? text(tool.path)
                                           : text(tool.path) ?? text(argumentString("path", in: tool.input))
            let object = path.map(shortPath)
            switch tool.name {
            case "read": return ActionParts(kind: .read, done: "Read", doing: "reading", object: object ?? "file", path: path)
            case "write":
                let created = tool.added != nil && (tool.removed ?? 0) == 0
                return ActionParts(kind: .write, done: created ? "Created" : "Wrote", doing: "writing", object: object ?? "file", path: path)
            case "edit": return ActionParts(kind: .write, done: "Edited", doing: "editing", object: object ?? "file", path: path)
            default: return ActionParts(kind: .list, done: "Listed", doing: "listing", object: object ?? "directory", path: path)
            }
        case "bash":
            // A command can carry a whole heredoc; the row shows its first line.
            let command = firstLine(text(argumentString("command", in: tool.input)) ?? tool.input)
            return ActionParts(kind: .command, done: "Ran", doing: "running", object: command.isEmpty ? "command" : command)
        case "find", "grep":
            return ActionParts(kind: .search, done: "Searched", doing: "searching", object: text(argumentString("pattern", in: tool.input)) ?? "files")
        case "mcp":
            // The meta-tool's action says what happened: a server list, schema loads or one invocation.
            let input = parseInput(tool.input)
            let action = text(input["action"]) ?? "invoke", server = text(input["server"])
            if action == "list" { return ActionParts(kind: .mcp, done: "Listed", doing: "listing", object: server.map { "tools on \($0)" } ?? "MCP servers") }
            if action == "describe" {
                let count = (input["targets"] as? [Any])?.count ?? 0
                return ActionParts(kind: .mcp, done: "Loaded", doing: "loading", object: count > 0 ? "\(count) tool \(count == 1 ? "schema" : "schemas")" : "tool schemas")
            }
            return ActionParts(kind: .mcp, done: "Called", doing: "calling", object: "\(server ?? "server") · \(text(input["tool"]) ?? "call")")
        default: return ActionParts(kind: .other, done: "Used", doing: "using", object: tool.name)
        }
    }
// TranscriptActivity.swift:336-339
    struct FileLink: Equatable, Sendable {
        let path: String
        let lines: ClosedRange<Int>?
    }
// TranscriptActivity.swift:349-368
    static func fileLink(_ tool: ToolView) -> FileLink? {
        guard ["read", "write", "edit"].contains(tool.name) else { return nil }
        let outcome = outcome(of: tool)
        let path: String
        if let resolved = text(tool.path) {
            path = resolved
        } else {
            guard outcome != .running, tool.inputTruncated != true, let argument = text(argumentString("path", in: tool.input)) else { return nil }
            path = argument
        }
        guard outcome == .done else { return FileLink(path: path, lines: nil) }
        if tool.name == "read" {
            let input = parseInput(tool.input)
            guard input["offset"] != nil || input["limit"] != nil, !tool.output.hasPrefix("Read image file [") else { return FileLink(path: path, lines: nil) }
        }
        if let first = tool.line, first > 0 { return FileLink(path: path, lines: first...max(first, tool.lastLine ?? first)) }
        guard tool.name == "read" else { return FileLink(path: path, lines: nil) }
        let first = TranscriptReadCardText.firstLine(of: tool.input), shown = TranscriptReadCardText.window(of: tool.output).lines.count
        return FileLink(path: path, lines: shown > 0 ? first...(first + shown - 1) : nil)
    }
// TranscriptActivity.swift:406-418
    static func formatDuration(_ ms: Double) -> String {
        guard DurationObservation.valid(ms) != nil else { return "" }
        // A tenth that rounds up to the second is written as the second:
        // 990 ms is "1s", never "1.0s".
        if (ms / 100).rounded() < 10 { return String(format: "%.1fs", ms / 1000) }
        // Retained history can contain finite values outside Int's range.
        guard let seconds = Int(exactly: (ms / 1000).rounded()) else { return "" }
        if seconds < 60 { return "\(seconds)s" }
        let minutes = seconds / 60, rest = seconds % 60
        if minutes < 60 { return rest > 0 ? "\(minutes)m \(rest)s" : "\(minutes)m" }
        let hours = minutes / 60, restMinutes = minutes % 60
        return restMinutes > 0 ? "\(hours)h \(restMinutes)m" : "\(hours)h"
    }
}

enum TranscriptToolRow {
// TranscriptRowParts.swift:14-21
    nonisolated static func state(of tool: ToolView) -> TranscriptRowState {
        switch TranscriptActivity.outcome(of: tool) {
        case .running: return .running
        case .cancelled, .unknown: return .stopped
        case .failed: return .failed
        case .done: return .ok
        }
    }
// TranscriptRowParts.swift:30-32
    nonisolated static func title(of tool: ToolView) -> String {
        title(TranscriptActivity.actionParts(tool), outcome: TranscriptActivity.outcome(of: tool))
    }
// TranscriptRowParts.swift:33-35
    nonisolated private static func title(_ parts: TranscriptActivity.ActionParts, outcome: ActionOutcome) -> String {
        outcome == .unknown || outcome == .cancelled ? TranscriptActivity.describe(parts, outcome: outcome).verb : parts.done
    }
// TranscriptRowParts.swift:38
    nonisolated static func summary(of tool: ToolView) -> String { summary(of: tool, object: TranscriptActivity.actionParts(tool).object) }
// TranscriptRowParts.swift:39-42
    nonisolated private static func summary(of tool: ToolView, object: String) -> String {
        guard state(of: tool) == .failed, !tool.output.isEmpty else { return object }
        return TranscriptActivity.firstLine(tool.output)
    }
// TranscriptRowParts.swift:46-49
    nonisolated static func elapsed(of tool: ToolView) -> String? {
        guard TranscriptActivity.outcome(of: tool) != .running, let ms = tool.durationMs, ms >= 50 else { return nil }
        return TranscriptActivity.formatDuration(ms)
    }
// TranscriptRowParts.swift:53-57
    nonisolated static func suffix(of tool: ToolView) -> String? {
        let change = tool.added != nil || tool.removed != nil ? "+\(tool.added ?? 0) −\(tool.removed ?? 0)" : nil
        guard TranscriptActivity.outcome(of: tool) == .unknown else { return change }
        return [change, "· outcome unknown"].compactMap { $0 }.joined(separator: " ")
    }
// TranscriptRowParts.swift:62-77
    struct Model: Equatable {
        let icon: String
        let title: String
        let summary: String
        let suffix: String?
        let state: TranscriptRowState
        let trailing: String?
        let help: String
        /// Only a summary that is the path is its link: a failure's words are
        /// not, though the row opens the file.
        let linksSummary: Bool
        let description: ActionDescription
        let outcome: ActionOutcome
        /// The call's file, when it has one: what the link opens.
        let file: TranscriptActivity.FileLink?
    }
// TranscriptRowParts.swift:78-87
    nonisolated static func model(of tool: ToolView) -> Model {
        let parts = TranscriptActivity.actionParts(tool)
        let outcome = TranscriptActivity.outcome(of: tool)
        let description = TranscriptActivity.describe(parts, outcome: outcome)
        let summary = summary(of: tool, object: description.object)
        return Model(icon: actionSymbol(description.kind), title: title(parts, outcome: outcome), summary: summary,
                     suffix: suffix(of: tool), state: state(of: tool), trailing: elapsed(of: tool),
                     help: description.path ?? description.object, linksSummary: summary == description.object,
                     description: description, outcome: outcome, file: TranscriptActivity.fileLink(tool))
    }
}
