//! How many cells a scalar takes: 0 for marks, joiners and controls, 2 for
//! East Asian wide characters and emoji, otherwise 1 (Swift 0.1.122
//! TerminalCharacterWidth.swift). A shell's line editor moves its cursor by
//! the widths it counts itself, so the table is Swift's own answer for every
//! scalar, generated by the oracle, not a newer Unicode's.

/// Cells `scalar` takes.
pub fn width(scalar: char) -> u8 {
    let value = u32::from(scalar);
    if (0x20..0x7f).contains(&value) {
        return 1;
    }
    let table = super::width_table::RANGES;
    match table.binary_search_by(|&(low, high, _)| {
        if value < low {
            std::cmp::Ordering::Greater
        } else if value > high {
            std::cmp::Ordering::Less
        } else {
            std::cmp::Ordering::Equal
        }
    }) {
        Ok(index) => table[index].2,
        Err(_) => 1,
    }
}
