#!/usr/bin/env python3
"""Copy Swift 0.1.122's tool-row declarations, unchanged, into one file.

Each declaration is found by the line that opens it and copied through its
matching closing brace (string literals skipped, so `"{"` does not count).
Usage: extract.py <pi-app checkout> > swift-src/Extracted.swift
"""
import re
import sys

ROOT = sys.argv[1].rstrip("/") + "/apps/macos/PiApp/Transcript/"


def declaration(path, opener, single_line=False):
    lines = open(ROOT + path, encoding="utf-8").read().split("\n")
    for start, line in enumerate(lines):
        if re.search(opener, line):
            break
    else:
        raise SystemExit(f"{path}: no line matches {opener!r}")
    if single_line:
        return f"// {path}:{start + 1}\n" + lines[start]
    depth, seen, out = 0, False, []
    for number in range(start, len(lines)):
        text = lines[number]
        out.append(text)
        quoted = escaped = False
        for ch in text:
            if quoted:
                if escaped:
                    escaped = False
                elif ch == "\\":
                    escaped = True
                elif ch == '"':
                    quoted = False
                continue
            if ch == '"':
                quoted = True
            elif ch == "{":
                depth += 1
                seen = True
            elif ch == "}":
                depth -= 1
        if seen and depth == 0:
            return f"// {path}:{start + 1}-{number + 1}\n" + "\n".join(out)
    raise SystemExit(f"{path}: {opener!r} never closes")


A = "TranscriptActivity.swift"
P = "TranscriptRowParts.swift"
top = [
    declaration(A, r"^enum DurationObservation"),
    declaration(A, r"^enum ActionKind", True),
    declaration(A, r"^struct ActionDescription"),
    declaration(A, r"^enum ActionOutcome", True),
    declaration(A, r"^enum ToolState"),
    declaration("TranscriptRowChrome.swift", r"^enum TranscriptRowState"),
    declaration("TranscriptRows.swift", r"^nonisolated func actionSymbol"),
    declaration(P, r"^enum TranscriptReadCardText"),
    declaration("ToolCallSummary.swift", r"^struct ToolCallSummary"),
]
activity = [
    declaration(A, r"static func parseInput", True),
    declaration(A, r"private static let argumentCountLock", True),
    declaration(A, r"nonisolated\(unsafe\) private static var argumentBytes", True),
    declaration(A, r"static func decodeArguments"),
    declaration(A, r"private static func repairedArguments"),
    declaration(A, r"private enum JSONByte"),
    declaration(A, r"static func argumentString"),
    declaration(A, r"private static func member"),
    declaration(A, r"static func shortPath"),
    declaration(A, r"static func firstLine"),
    declaration(A, r"private static let blank", True),
    declaration(A, r"private static func text\("),
    declaration(A, r"static func outcome\(of tool"),
    declaration(A, r"private static func conjugate"),
    declaration(A, r"static func describe\(_ tool", True),
    declaration(A, r"static func describe\(_ parts"),
    declaration(A, r"struct ActionParts"),
    declaration(A, r"static func actionParts"),
    declaration(A, r"struct FileLink"),
    declaration(A, r"static func fileLink"),
    declaration(A, r"static func formatDuration"),
]
row = [
    declaration(P, r"nonisolated static func state\(of tool"),
    declaration(P, r"nonisolated static func title\(of tool"),
    declaration(P, r"nonisolated private static func title\("),
    declaration(P, r"nonisolated static func summary\(of tool: ToolView\) -> String \{ summary", True),
    declaration(P, r"nonisolated private static func summary\(of tool"),
    declaration(P, r"nonisolated static func elapsed"),
    declaration(P, r"nonisolated static func suffix"),
    declaration(P, r"struct Model: Equatable"),
    declaration(P, r"nonisolated static func model\(of tool"),
]
print("// Generated by extract.py from Swift 0.1.122 (pi-app 6319e368). Do not edit.")
print("import Foundation\n")
print("\n\n".join(top))
print("\nenum TranscriptActivity {")
print("\n".join(activity))
print("}\n\nenum TranscriptToolRow {")
print("\n".join(row))
print("}")
