use super::*;
fn rows(texts:&[&str])->Arc<Session>{Arc::new(Session{id:"chat".into(),active_reply:None,messages:texts.iter().enumerate().map(|(i,t)|bello_agent_core::Message{id:i.to_string(),text:t.to_string(),state:"complete".into(),reasoning:"SECRET".into()}).collect()})}
#[test] fn equal_length_replacement(){let a=rows(&["abcd"]);let s=Snapshot::new(a.clone());let mut b=(*a).clone();b.messages[0].text="wxyz".into();assert!(!s.matches(&Arc::new(b)));}
#[test] fn exact_limit(){let t="x".repeat(8*1024*1024);let s=Snapshot::new(rows(&[&t,"x"]));let c=AtomicBool::new(false);assert_eq!(s.collect(1,1,&c).unwrap().len(),8*1024*1024);assert!(s.collect(1,2,&c).is_err());}
#[test] fn active_stream_exclusion(){let mut a=(*rows(&["visible","stream"])).clone();a.active_reply=Some("1".into());a.messages[1].state="streaming".into();let s=Snapshot::new(Arc::new(a));assert_eq!(s.search("",0).unwrap().total,1);assert_eq!(s.collect(1,1,&AtomicBool::new(false)).unwrap(),"visible");}
#[test] fn hidden_never_searched(){let s=Snapshot::new(rows(&["visible"]));assert!(s.search("SECRET",0).unwrap().hits.is_empty());assert_eq!(s.collect(1,1,&AtomicBool::new(false)).unwrap(),"visible");}
#[test] fn unicode_limits(){let s=Snapshot::new(rows(&["CAFÉ"]));assert_eq!(s.search("cafe\u{301}",0).unwrap().hits.len(),1);assert!(s.search(&"e\u{301}".repeat(256),0).is_ok());assert!(s.search(&"e\u{301}".repeat(257),0).is_err());assert!(s.search(&format!("a{}","\u{301}".repeat(16384)),0).is_err());}
#[test] fn cancellation_never_success(){let s=Snapshot::new(rows(&["match"]));let c=AtomicBool::new(true);assert!(s.search_cancelled("match",0,&c).is_err());assert!(s.collect(1,1,&c).is_err());}
#[test] fn differential_normalization_match(){let alphabet=['a','A','\u{301}','é','e','İ','ı','ß','Σ','σ','ς','\u{f73}','\u{345}','\u{1100}','\u{1161}'];let c=AtomicBool::new(false);for i in 0..alphabet.len(){for j in 0..alphabet.len(){for k in 0..alphabet.len(){let text=format!("{}{}{}",alphabet[i],alphabet[j],alphabet[k]);let s=Snapshot::new(rows(&[&text]));let norm:String=text.nfc().flat_map(char::to_lowercase).nfc().collect();for q in ["a","é","e\u{301}","i","σ","\u{345}"]{let nq:String=q.nfc().flat_map(char::to_lowercase).nfc().collect();assert_eq!(!s.search_cancelled(q,0,&c).unwrap().hits.is_empty(),norm.contains(&nq),"{text:?}/{q:?}");}}}}}
#[test] fn occurrence_counts_nonoverlapping(){let s=Snapshot::new(rows(&["aaaaa","Aa-aa-aA","CAFÉ cafe\u{301} café"]));assert_eq!(s.search("aa",0).unwrap().hits.iter().map(|h|h.count).collect::<Vec<_>>(),vec![Some(2),Some(3)]);assert_eq!(s.search("cafe\u{301}",0).unwrap().hits[0].count,Some(3));assert!(s.search("",0).unwrap().hits.iter().all(|h|h.count==Some(0)));}
#[test] fn occurrence_count_matches_normalized_nonoverlap_reference(){let alphabet=['a','A','b','é','\u{301}','İ'];let queries=["a","aa","aaa","ab","aba","b","é","e\u{301}","i","\u{301}"];for n in 0..6usize.pow(5){let mut number=n;let mut text=String::new();for _ in 0..5{text.push(alphabet[number%6]);number/=6;}let s=Snapshot::new(rows(&[&text]));let norm:String=text.nfc().flat_map(char::to_lowercase).nfc().collect();for q in queries{let nq:String=q.nfc().flat_map(char::to_lowercase).nfc().collect();let expected=norm.match_indices(&nq).count();let page=s.search(q,0).unwrap();let actual=page.hits.first().map_or(0,|h|h.count.unwrap());assert_eq!(actual,expected,"{text:?}/{q:?}");}}}
#[test] fn counts_do_not_consume_hit_page_limit(){let texts:Vec<_>=(0..101).map(|_|"aaaaa").collect();let s=Snapshot::new(rows(&texts));let p=s.search("aa",0).unwrap();assert_eq!(p.hits.len(),100);assert_eq!(p.next,Some(100));assert!(p.hits.iter().all(|h|h.count==Some(2)));assert_eq!(s.search("aa",100).unwrap().hits[0].position,101);}
