// Generated by extract.py from Swift 0.1.122 (pi-app 6319e368). Do not edit.
import Foundation

// TranscriptCards.swift:12-37
enum TranscriptCardMetrics {
    /// How tall one section of the IN/OUT card grows before it scrolls.
    static let sectionCap: CGFloat = 150
    /// A command's output before it scrolls.
    static let terminalCap: CGFloat = 224
    /// Lines of a diff before the middle collapses.
    static let diffLines = 12
    /// Lines of a read window before the middle collapses.
    static let readLines = 12
    /// The gutter the IN/OUT labels sit in.
    static let gutter: CGFloat = 30

    /// The head/tail split for a capped list: how many rows are hidden,
    /// whether it caps at all, and how the visible rows divide.
    /// A list one line over its cap is drawn whole: the line saying "1 more"
    /// would take the room of the line it hides, and hide it for nothing.
    static func headTail(total: Int, maxLines: Int, expanded: Bool) -> (hidden: Int, capped: Bool, head: Int, tail: Int) {
        let hidden = total - maxLines
        let head = Int((Double(maxLines) / 2).rounded(.up))
        return (hidden, collapses(hidden: hidden) && !expanded, head, maxLines - head)
    }
    /// Whether a list hides enough to be worth collapsing at all.
    static func collapses(hidden: Int) -> Bool { hidden > 1 }
    /// "… 12 more lines", in the singular for one.
    static func moreLines(_ hidden: Int) -> String { "… \(hidden) more line\(hidden == 1 ? "" : "s")" }
}

// TranscriptNativeCards.swift:10-15
func transcriptNumber(_ value: Int, _ locale: Locale) -> String {
    let formatter = NumberFormatter()
    formatter.numberStyle = .decimal
    formatter.locale = locale
    return formatter.string(from: NSNumber(value: value)) ?? "\(value)"
}

// TranscriptRowParts.swift:183-211
enum TranscriptReadCardText {
    /// A read's result as the card reads it: its lines, and the host's note
    /// when the read stopped short of the file. The host ends a bounded read
    /// with "[Truncated. N total lines; read another range.]": a note about
    /// the file, not its next line.
    nonisolated static func window(of text: String) -> (lines: [String], note: String?) {
        var lines = text.isEmpty ? [] : text.components(separatedBy: "\n")
        if let last = lines.last, last.hasPrefix("[Truncated."), last.hasSuffix("]") {
            let note = String(last.dropFirst().dropLast())
            lines.removeLast()
            return (lines, note)
        }
        return (lines, nil)
    }
    /// The line a read started at, from its arguments: the host's `offset`, a
    /// 1-based line number, or the first line when the read named none.
    nonisolated static func firstLine(of input: String) -> Int {
        guard let offset = TranscriptActivity.parseInput(input)["offset"] as? NSNumber,
              CFGetTypeID(offset) != CFBooleanGetTypeID() else { return 1 }
        let value = offset.doubleValue
        guard value.isFinite, value >= 1, value.rounded() == value, value <= 10_000_000 else { return 1 }
        return Int(value)
    }
    /// "Showing 12 of 340 lines", and nothing at all when it is showing all
    /// of them: a card that is complete should not say so on every read.
    nonisolated static func window(shown: Int, total: Int) -> String {
        shown >= total ? "\(total) line\(total == 1 ? "" : "s")" : "Showing \(shown) of \(total) lines"
    }
}

// TranscriptTurnFold.swift:7-19
enum TranscriptDisplayMode: String, CaseIterable, Sendable, Codable {
    /// A finished turn keeps every row it had while it ran.
    case normal
    /// A finished turn's work folds behind one line above its answer.
    case compact
    var label: String { self == .normal ? "Normal" : "Compact" }
    var detail: String {
        self == .normal
            ? "A finished turn keeps every tool call and thought on screen."
            : "A finished turn folds its work behind one line above the answer."
    }
    static let fallback = TranscriptDisplayMode.compact
}

// TranscriptTurnFold.swift:46-70
struct TurnFoldSpec: Equatable, Sendable {
    /// The id of the reader's message that opened this display turn: the key
    /// the reader's choice is kept under, so opening a turn survives
    /// streaming, paging and a chat switch. It is a row on the page by
    /// construction, so it lives exactly as long as the turn does, and it is
    /// unique even when a steer puts two display turns under one task root.
    var group: String
    /// The response whose words are the answer. Its prose never folds.
    var answerResponseID: String
    var toolCalls = 0
    var messages = 0
    var subagents = 0

    /// "3 tool calls · 1 message", "2 subagents", and — when a turn only
    /// thought — the line that says so without counting anything.
    var label: String {
        var parts: [String] = []
        if toolCalls > 0 { parts.append("\(toolCalls) tool call\(toolCalls == 1 ? "" : "s")") }
        if messages > 0 { parts.append("\(messages) message\(messages == 1 ? "" : "s")") }
        if subagents > 0 { parts.append("\(subagents) subagent\(subagents == 1 ? "" : "s")") }
        return parts.isEmpty ? "Thought for a while" : parts.joined(separator: " · ")
    }
    /// A delegation call is a subagent, not a tool call, wherever its name says so.
    static func isSubagent(_ name: String) -> Bool { name == "subagent" || name.hasPrefix("subagent_") }
}

// ToolCallSummary.swift:5-42
struct ToolCallSummary: Equatable, Sendable {
    var total = 0
    var failed = 0
    var skipped = 0
    var uncertain = 0
    var preparing = false
    var partial = false

    init(rows: [TranscriptMessage]) {
        var owners = Set<String>()
        for row in rows where row.role == "assistant" && owners.insert(row.id).inserted {
            let cards = row.tools ?? []
            let confirmed = cards.filter { $0.state != "preparing" }
            if let count = row.toolCallCount, count >= 0 { total += count }
            else { total += confirmed.count; partial = partial || row.truncated == true }
            preparing = preparing || cards.contains { $0.state == "preparing" }
            for card in confirmed {
                switch card.state {
                case "failed": failed += 1
                case "cancelled", "skipped": skipped += 1
                case "recorded", "unknown", "interrupted": uncertain += 1
                default: break
                }
            }
        }
    }
    init(tools: [ToolView]) { self.init(rows: [.init(id: "summary", role: "assistant", text: "", tools: tools)]) }
    var label: String? { label(reasoned: false) }
    func label(reasoned: Bool) -> String? {
        var parts: [String] = reasoned ? ["Reasoned"] : []
        if total > 0 { parts.append((partial ? "at least " : "") + "\(total) tool " + (total == 1 ? "call" : "calls")) }
        if failed > 0 { parts.append("\(failed) failed") }
        if skipped > 0 { parts.append("\(skipped) skipped") }
        if uncertain > 0 { parts.append("\(uncertain) outcome unknown") }
        if preparing { parts.append("Preparing tool call…") }
        return parts.isEmpty ? nil : parts.joined(separator: " · ")
    }
}

enum TaskTranscriptPlan {
// TaskTranscriptPlan.swift:24
    static func visible(_ text: String) -> Bool { text.unicodeScalars.contains { !whitespace.contains($0) } }
// TaskTranscriptPlan.swift:25
    private static let whitespace = CharacterSet.whitespacesAndNewlines
}
