#!/usr/bin/env python3
"""Copy Swift 0.1.122's pure transcript-polish declarations, unchanged.

Each declaration is found by the line that opens it and copied through its
matching closing brace (string literals skipped, so `"{"` does not count).
Usage: extract.py <pi-app checkout> > swift-src/Extracted.swift
"""
import re
import sys

ROOT = sys.argv[1].rstrip("/") + "/apps/macos/PiApp/Transcript/"


def declaration(path, opener, single_line=False):
    lines = open(ROOT + path, encoding="utf-8").read().split("\n")
    for start, line in enumerate(lines):
        if re.search(opener, line):
            break
    else:
        raise SystemExit(f"{path}: no line matches {opener!r}")
    if single_line:
        return f"// {path}:{start + 1}\n" + lines[start]
    depth, seen, out = 0, False, []
    for number in range(start, len(lines)):
        text = lines[number]
        out.append(text)
        quoted = escaped = False
        for ch in text:
            if quoted:
                if escaped:
                    escaped = False
                elif ch == "\\":
                    escaped = True
                elif ch == '"':
                    quoted = False
                continue
            if ch == '"':
                quoted = True
            elif ch == "{":
                depth += 1
                seen = True
            elif ch == "}":
                depth -= 1
        if seen and depth == 0:
            return f"// {path}:{start + 1}-{number + 1}\n" + "\n".join(out)
    raise SystemExit(f"{path}: {opener!r} never closes")


parts = [
    declaration("TranscriptCards.swift", r"^enum TranscriptCardMetrics"),
    declaration("TranscriptNativeCards.swift", r"^func transcriptNumber"),
    declaration("TranscriptRowParts.swift", r"^enum TranscriptReadCardText"),
    declaration("TranscriptTurnFold.swift", r"^enum TranscriptDisplayMode"),
    declaration("TranscriptTurnFold.swift", r"^struct TurnFoldSpec"),
    declaration("ToolCallSummary.swift", r"^struct ToolCallSummary"),
]
plan = [
    declaration("TaskTranscriptPlan.swift", r"static func visible\(_ text: String\)", True),
    declaration("TaskTranscriptPlan.swift", r"private static let whitespace = ", True),
]
print("// Generated by extract.py from Swift 0.1.122 (pi-app 6319e368). Do not edit.")
print("import Foundation\n")
print("\n\n".join(parts))
print("\nenum TaskTranscriptPlan {")
print("\n".join(plan))
print("}")
